apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp # This does not have to match with the template
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp # Select pods with this environment variables defined in template below
  template:
    # Using nginx.kube.yml example from PodsWithYAML folder
    metadata:
      name: nginx-2
      labels:
        env: production
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx
        # - name: busybox
        #   image: busybox
